version: '3.8'

services:
  backend:
    build: ./node-backend
    ports:
      - "3000:3000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "8008:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: xuatqc
      MYSQL_PASSWORD: 20150601
    ports:
      - "3307:3307"
    networks:
      - app_network

networks:
  app_network:
